"""
PRD & User Story generator.

Turns discovered pain points + verbatim evidence into a draft remediation PRD
for prioritization discussions — not outcome forecasts.
"""

from __future__ import annotations

from typing import Any

import pandas as pd

from services.evidence_chain import fetch_topic_evidence, summarize_topic_evidence


def _slug(text: str) -> str:
    return "".join(c if c.isalnum() else "-" for c in text.lower()).strip("-")[:48]


def generate_user_stories(
    df: pd.DataFrame,
    roadmap_df: pd.DataFrame,
    *,
    max_items: int = 5,
) -> list[dict[str, Any]]:
    """Generate user stories for top roadmap items."""
    stories: list[dict[str, Any]] = []
    for _, row in roadmap_df.head(max_items).iterrows():
        topic = str(row["Core Pain Point"])
        priority = str(row["Priority"])
        action = str(row.get("Recommended Action", ""))
        evidence = fetch_topic_evidence(df, topic, max_rows=2)
        quote = str(evidence.iloc[0]["text"])[:220] if not evidence.empty else ""
        summary = summarize_topic_evidence(df, topic)

        stories.append(
            {
                "id": f"US-{priority}-{_slug(topic)[:20]}",
                "priority": priority,
                "pain_point": topic,
                "title": f"Investigate / resolve: {topic}",
                "as_a": "user who hit this friction",
                "i_want": f"the product experience related to “{topic}” clarified and improved",
                "so_that": "I can complete my goal without this frustration",
                "acceptance_criteria": [
                    f"QA covers repro paths derived from {summary['total_count']} related complaints",
                    "User-facing states (error / empty / success) are explicit",
                    "Primary failure mode has a regression test",
                    "Evidence quotes for this theme are archived with the ticket",
                ],
                "engineering_notes": action,
                "evidence_quote": quote,
                "matching_reviews": summary["total_count"],
            }
        )
    return stories


def generate_prd_markdown(
    df: pd.DataFrame,
    roadmap_df: pd.DataFrame,
    *,
    product_name: str = "Product",
    max_items: int = 5,
    revenue_summary: dict[str, Any] | None = None,  # kept for API compat; ignored
) -> str:
    """Build a draft PRD focused on discovery, priority, and evidence."""
    stories = generate_user_stories(df, roadmap_df, max_items=max_items)
    lines: list[str] = [
        f"# PRD Draft — Pain Point Investigation ({product_name})",
        "",
        "## 1. Problem statement",
        "Users express concentrated negative sentiment around specific themes.",
        "This draft helps the team **discover issues, agree a priority order, and attach evidence**.",
        "It does **not** forecast retention or revenue outcomes.",
        "",
        "## 2. Goals",
        "- Make top complaint themes visible and evidence-backed",
        "- Agree a P0/P1/P2 draft for the next sprint discussion",
        "- Hand engineers clear user stories with verbatim quotes",
        "",
        "## 3. Scope — priority draft",
        "",
    ]
    for _, row in roadmap_df.head(max_items).iterrows():
        score = row.get("Priority Score", "")
        mentions = row.get("Mentions", "")
        lines.append(
            f"- **{row['Priority']} · {row['Core Pain Point']}** "
            f"(score {score}, {mentions} mentions) — {row['AI Diagnosis']}"
        )
    lines.append("")

    lines += ["## 4. User stories", ""]
    for s in stories:
        lines += [
            f"### {s['id']} — {s['title']}",
            f"**Priority:** {s['priority']} · **Evidence reviews:** {s['matching_reviews']}",
            "",
            f"> As a {s['as_a']}, I want {s['i_want']}, so that {s['so_that']}.",
            "",
            "**Acceptance criteria**",
        ]
        for ac in s["acceptance_criteria"]:
            lines.append(f"- [ ] {ac}")
        lines += ["", f"**Notes:** {s['engineering_notes']}", ""]
        if s["evidence_quote"]:
            lines += ["**Verbatim evidence**", f"> \"{s['evidence_quote']}\"", ""]

    lines += [
        "## 5. Out of scope",
        "- Claiming how much retention or revenue a fix will recover",
        "- Causal attribution across product analytics without a dedicated study",
        "",
        "## 6. How we will know the work mattered (observation, not prediction)",
        "- Theme mention share among negatives in the next review cohort",
        "- Average rage index for remapped themes",
        "- Qualitative follow-up interviews on P0 themes",
        "",
        "_Generated by InsightOptima — discovery + priority draft + evidence._",
    ]
    return "\n".join(lines)
